
/*
Al hacer clic en un botón, el sistema debe crear un personaje con un nombre, edad, raza (humano, elfo, enano, etc.), y una habilidad especial (como volar, invisibilidad, superfuerza, etc.), todos ellos aleatorios.
*/

export const names = [
    "Aragorn",
    "Legolas",
    "Gandalf",
    "Frodo",
    "Samwise",
    "Gollum",
    "Bilbo",
    "Éowyn",
    "Boromir",
    "Galadriel",
    "Sauron",
    "Dumbledore",
    "Hermione",
    "Harry",
    "Ron",
    "Draco",
    "Luna",
    "Neville",
    "Voldemort",
    "Rubeus",
    "Gandalf",
    "Lyra",
    "Will",
    "Pan",
    "Aslan",
    "Jareth",
    "Sarah",
    "Narnia",
    "Puck",
    "Titania",
    "Rumpelstiltskin",
    "Rincewind",
    "Cthulhu",
    "Elric",
    "Stormbringer",
    "Yoda",
    "Leia",
    "Luke",
    "Chewbacca",
    "Gimli",
    "Faramir",
    "Thorin",
    "Dori",
    "Nori",
    "Kili",
    "Bilbo",
    "Smeagol",
    "Tauriel",
    "Loki"
]

export const races = [
    "Elfos",
    "Enanos",
    "Humanos",
    "Orcos",
    "Dragones",
    "Sirenas",
    "Trolls",
    "Gnomos",
    "Vampiros",
    "Hombres lobo",
    "Demonios",
    "Fantasma",
    "Hadas",
    "Centauros",
    "Gigantes",
    "Kraken",
    "Elementales",
    "Faunos",
    "Drows",
    "Ángeles"
]

export const skills = [
    "Magia",
    "Sigilo",
    "Superfuerza",
    "Curación",
    "Persuasión",
    "Tiro con arco",
    "Tecnología avanzada",
    "Control del fuego",
    "Transformación",
    "Telepatía"
]
